version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: express
    ports:
      - ${PORT}:${PORT}
    # volumes:
    #   - .:/usr/src/app
    #   - /usr/src/app/node_modules


# volumes:
#   node_modules:

# docker compose up --build to rebuild on code change